#!/usr/bin/env bash
set -e
shopt -s extglob

catnip_help() {
	echo "Help string for catnip"
	exit 0
}

cmake_list() {
	local IFS=";"
	echo "$*"
}

args=()
flags=()
cache=()

while [[ $# -gt 0 ]]; do
	case "$1" in
	--help)
		catnip_help
		;;
	--*)
		echo "Invalid option: $1"
		catnip_help
		;;
	-*)
		OPTIND=1
		while getopts "S:B:D:U:T:t:pvf?h" opt; do
			case "$opt" in
			h|\?)
				catnip_help
				;;
			S)
				flags+=("-DCATNIP_ROOT:STRING=${OPTARG}")
				;;
			B)
				flags+=("-DCATNIP_BUILD_DIR:STRING=${OPTARG}")
				;;
			D)
				case "${OPTARG}" in
				+([a-zA-Z0-9_])?(:BOOL|:FILEPATH|:PATH|:STRING|:INTERNAL)=*)
					cache+=("${OPTARG}")
					;;
				*)
					echo "Invalid cache entry: ${OPTARG}"
					catnip_help
					;;
				esac
				;;
			U)
				cache+=("${OPTARG}:UNSET=")
				;;
			[Tt])
				flags+=("-DCATNIP_DEFAULT_TOOLSET:STRING=${OPTARG}")
				;;
			p)
				flags+=("-DCATNIP_PACKAGE_SELECTORS:BOOL=ON")
				;;
			v)
				flags+=("-DCATNIP_VERBOSE:BOOL=ON")
				;;
			f)
				flags+=("-DCATNIP_FORCE_FLAG:BOOL=ON")
				;;
			esac
		done
		shift $((OPTIND-1))
		;;
	+([a-zA-Z0-9_.]))
		args+=("$1")
		shift
		;;
	*)
		echo "Invalid argument: $1"
		catnip_help
		;;
	esac
done

flags+=("-DCATNIP_CACHE:STRING=$(cmake_list "${cache[@]}")")
flags+=("-DCATNIP_ARGV:STRING=$(cmake_list "${args[@]}")")

exec cmake "${flags[@]}" -P ${DEVKITPRO}/cmake/catnip-main.cmake
